site_name: Langton's Ant
site_description: Prosta strona statyczna o Langton's Ant stworzona przy użyciu MkDocs
nav:
  - Strona główna: index.md
  - O projekcie: about.md
  - Kod: code.md
theme:
  name: readthedocs