site_name: Langton's Ant
site_description: Prosta strona statyczna o Langton's Ant stworzona przy użyciu MkDocs
nav:
  - Strona główna: index.md
  - O projekcie: about.md
  - Kod: code.md
  - Ciekawostki: interesting.md
  - Deweloperskie (work in progress): deweloperskie.md
theme:
  name: material
  palette:

    # Light mode
    - scheme: default
      primary: deep orange
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      primary: deep orange
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

